import React, { useState } from 'react';
import { 
  Users, Plus, Search, Edit, Trash2, Mail, Phone, MapPin, 
  Briefcase, ArrowLeft, FileText, Download, Check, RefreshCw,
  Award, TrendingUp, AlertCircle, CheckCircle, Printer, FileDown
} from 'lucide-react';
import { Client, Invoice, UserProfile } from '../types';
import { formatCurrency, formatDateIndonesian } from '../utils';
import ConfirmModal from './ConfirmModal';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { showToast } from '../utils/toast';

interface ClientManagementProps {
  user: UserProfile;
  clients: Client[];
  invoices: Invoice[];
  onAddClient: (client: Client) => void;
  onEditClient: (client: Client) => void;
  onDeleteClient: (id: string) => void;
  onFeatureBlocked?: (featureName: string) => void;
}

export default function ClientManagement({
  user, clients, invoices, onAddClient, onEditClient, onDeleteClient, onFeatureBlocked
}: ClientManagementProps) {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedClient, setSelectedClient] = useState<Client | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [editingClient, setEditingClient] = useState<Client | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [invoiceFilter, setInvoiceFilter] = useState<'Semua' | 'Lunas' | 'Pending'>('Semua');

  // Confirmation Dialog State
  const [confirmDeleteState, setConfirmDeleteState] = useState<{
    isOpen: boolean;
    clientId?: string;
    clientName?: string;
  }>({
    isOpen: false
  });

  const triggerDeleteClient = (id: string, name: string) => {
    setConfirmDeleteState({
      isOpen: true,
      clientId: id,
      clientName: name
    });
  };

  const executeDeleteClient = () => {
    if (confirmDeleteState.clientId) {
      onDeleteClient(confirmDeleteState.clientId);
    }
  };

  // Form states
  const [name, setName] = useState('');
  const [businessName, setBusinessName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState('');

  const handleOpenAddForm = () => {
    const isExpired = user.subscription.status === 'expired' || new Date(user.subscription.expiryDate) < new Date();
    if (isExpired && onFeatureBlocked) {
      onFeatureBlocked('Penambahan Klien Baru');
      return;
    }
    setEditingClient(null);
    setName('');
    setBusinessName('');
    setEmail('');
    setPhone('');
    setAddress('');
    setFormOpen(true);
  };

  const handleOpenEditForm = (client: Client) => {
    setEditingClient(client);
    setName(client.name);
    setBusinessName(client.businessName || '');
    setEmail(client.email);
    setPhone(client.phone);
    setAddress(client.address);
    setFormOpen(true);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !email) {
      showToast('Nama dan Email wajib diisi.', 'warning');
      return;
    }

    const isExpired = user.subscription.status === 'expired' || new Date(user.subscription.expiryDate) < new Date();
    if (!editingClient && isExpired) {
      if (onFeatureBlocked) onFeatureBlocked('Penambahan Klien Baru');
      return;
    }

    if (editingClient) {
      const updated: Client = {
        ...editingClient,
        name,
        businessName,
        email,
        phone,
        address
      };
      onEditClient(updated);
    } else {
      const newClient: Client = {
        id: 'client_' + Math.random().toString(36).substring(2, 9),
        name,
        businessName,
        email,
        phone,
        address,
        createdAt: new Date().toISOString()
      };
      onAddClient(newClient);
    }
    setFormOpen(false);
  };

  const filteredClients = clients.filter(c => 
    c.name.toLowerCase().includes(searchTerm.toLowerCase()) || 
    (c.businessName && c.businessName.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  // Helper to calculate total revenue generated by a client
  const getClientStats = (clientId: string) => {
    const clientInvoices = invoices.filter(inv => inv.clientId === clientId);
    const count = clientInvoices.length;
    const paidSum = clientInvoices.filter(inv => inv.status === 'Lunas').reduce((acc, curr) => acc + curr.total, 0);
    const unpaidSum = clientInvoices.filter(inv => inv.status !== 'Lunas').reduce((acc, curr) => acc + curr.total, 0);
    return { count, paidSum, unpaidSum, clientInvoices };
  };

  // Helper to determine the loyalty level of the client
  const getClientTier = (paidSum: number) => {
    if (paidSum >= 15000000) {
      return { 
        label: 'Platinum Partner', 
        classes: 'bg-indigo-50 text-indigo-700 border border-indigo-100', 
        textColor: 'text-indigo-700',
        borderColor: 'border-indigo-100',
        bgColor: 'bg-indigo-50',
        badge: '🏆 Platinum',
        score: '⭐⭐⭐⭐⭐'
      };
    } else if (paidSum >= 5000000) {
      return { 
        label: 'Gold Client', 
        classes: 'bg-amber-50 text-amber-700 border border-amber-100', 
        textColor: 'text-amber-700',
        borderColor: 'border-amber-100',
        bgColor: 'bg-amber-50',
        badge: '✨ Gold',
        score: '⭐⭐⭐⭐'
      };
    } else if (paidSum >= 1000000) {
      return { 
        label: 'Silver Client', 
        classes: 'bg-slate-100 text-slate-700 border border-slate-200', 
        textColor: 'text-slate-700',
        borderColor: 'border-slate-200',
        bgColor: 'bg-slate-100',
        badge: '⭐ Silver',
        score: '⭐⭐⭐'
      };
    } else {
      return { 
        label: 'Mitra Baru', 
        classes: 'bg-emerald-50 text-emerald-700 border border-emerald-100', 
        textColor: 'text-emerald-700',
        borderColor: 'border-emerald-100',
        bgColor: 'bg-emerald-50',
        badge: '🌱 Baru',
        score: '⭐'
      };
    }
  };

  const formatSeqNumber = (num: number) => String(num).padStart(2, '0');

  // 1. Core Feature: PDF Export Client Directory (Landscape Corporate Format)
  const handleExportClientListPDF = () => {
    setIsExporting(true);
    setTimeout(() => {
      try {
        const doc = new jsPDF({
          orientation: 'landscape',
          unit: 'mm',
          format: 'a4'
        });

        // Background Slate/Indigo Banner for Top Executive Appeal
        doc.setFillColor(30, 41, 59); // Slate 800
        doc.rect(0, 0, 297, 40, 'F');

        // Document Titles
        doc.setTextColor(255, 255, 255);
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(18);
        doc.text('DIREKTORI & REKAPITULASI KLIEN BISNIS', 14, 15);
        
        doc.setFont('Helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(203, 213, 225); // Slate 300
        doc.text(`Dicetak pada: ${formatDateIndonesian(new Date().toISOString().split('T')[0])}`, 14, 22);
        doc.text(`Instansi Penerbit: ${user.businessName || user.fullName || 'Usaha Mandiri'}`, 14, 27);
        doc.text(`Alamat Kantor: ${user.address || '-'}`, 14, 32);

        // Aggregate analysis
        const totalClients = clients.length;
        let totalPaidAll = 0;
        let totalUnpaidAll = 0;
        let totalInvoicesAll = 0;

        clients.forEach(c => {
          const s = getClientStats(c.id);
          totalPaidAll += s.paidSum;
          totalUnpaidAll += s.unpaidSum;
          totalInvoicesAll += s.count;
        });

        // Summary statistics box in PDF
        doc.setFillColor(248, 250, 252); // Slate 50
        doc.setDrawColor(226, 232, 240); // Slate 200
        doc.rect(14, 48, 269, 22, 'FD');

        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139); // Slate 500
        doc.text('RINGKASAN EKSEKUTIF KLIEN:', 20, 53);

        doc.setFont('Helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(71, 85, 105);
        doc.text('Total Klien:', 20, 62);
        doc.setFont('Helvetica', 'bold');
        doc.setTextColor(15, 23, 42);
        doc.text(`${totalClients} Klien`, 40, 62);

        doc.setFont('Helvetica', 'normal');
        doc.setTextColor(71, 85, 105);
        doc.text('Total Transaksi:', 85, 62);
        doc.setFont('Helvetica', 'bold');
        doc.setTextColor(15, 23, 42);
        doc.text(`${totalInvoicesAll} Invoice`, 112, 62);

        doc.setFont('Helvetica', 'normal');
        doc.setTextColor(71, 85, 105);
        doc.text('Omset Lunas:', 155, 62);
        doc.setFont('Helvetica', 'bold');
        doc.setTextColor(22, 163, 74); // Green 600
        doc.text(formatCurrency(totalPaidAll), 180, 62);

        doc.setFont('Helvetica', 'normal');
        doc.setTextColor(71, 85, 105);
        doc.text('Piutang Berjalan:', 225, 62);
        doc.setFont('Helvetica', 'bold');
        doc.setTextColor(220, 38, 38); // Red 600
        doc.text(formatCurrency(totalUnpaidAll), 253, 62);

        // Client Table Headers & Data
        const tableHeaders = [
          ['No.', 'Nama Klien', 'Perusahaan / Bisnis', 'Kategori Klien', 'Email Klien', 'No. WhatsApp', 'Jml Inv', 'Omset Lunas', 'Outstanding Piutang']
        ];

        const tableData = filteredClients.map((c, index) => {
          const stats = getClientStats(c.id);
          const tier = getClientTier(stats.paidSum);
          return [
            formatSeqNumber(index + 1),
            c.name,
            c.businessName || 'Individu / Freelance',
            tier.label,
            c.email,
            c.phone || '-',
            stats.count,
            formatCurrency(stats.paidSum),
            formatCurrency(stats.unpaidSum)
          ];
        });

        autoTable(doc, {
          startY: 76,
          head: tableHeaders,
          body: tableData,
          theme: 'striped',
          headStyles: {
            fillColor: [15, 23, 42], // Slate 900
            textColor: [255, 255, 255],
            fontSize: 8.5,
            fontStyle: 'bold'
          },
          columnStyles: {
            0: { cellWidth: 12, halign: 'center' },
            1: { fontStyle: 'bold' },
            3: { fontStyle: 'bold' },
            6: { cellWidth: 15, halign: 'center' },
            7: { cellWidth: 32, halign: 'right' },
            8: { cellWidth: 32, halign: 'right' }
          },
          styles: {
            fontSize: 8,
            cellPadding: 3.5
          },
          didParseCell: (data) => {
            if (data.column.index === 0) {
              data.cell.styles.halign = 'center';
            } else if (data.column.index === 6) {
              data.cell.styles.halign = 'center';
            } else if (data.column.index === 7 || data.column.index === 8) {
              data.cell.styles.halign = 'right';
            } else {
              data.cell.styles.halign = 'left';
            }
          },
          alternateRowStyles: {
            fillColor: [248, 250, 252]
          },
          margin: { left: 14, right: 14 },
          didDrawPage: (data) => {
            // Header Divider
            doc.setFillColor(226, 232, 240);
            doc.rect(14, doc.internal.pageSize.height - 15, 269, 0.2, 'F');

            // Footer info
            doc.setFontSize(7.5);
            doc.setTextColor(148, 163, 184); // Slate 400
            doc.text(`Laporan Direktori Klien Resmi | Halaman ${data.pageNumber} dari ${(doc as any).internal.getNumberOfPages()}`, 14, doc.internal.pageSize.height - 10);
            doc.text(`KasirPintar v2.0 - Ekspor PDF Resmi Terstruktur`, doc.internal.pageSize.width - 14, doc.internal.pageSize.height - 10, { align: 'right' });
          }
        });

        doc.save(`Laporan_Direktori_Klien_${new Date().toISOString().split('T')[0]}.pdf`);
      } catch (error) {
        console.error('Error generating PDF:', error);
        showToast('Gagal mengekspor laporan PDF.', 'error');
      } finally {
        setIsExporting(false);
      }
    }, 500);
  };

  // 2. Core Feature: PDF Export Client Ledger/Statement of Account (Portrait Executive Format)
  const handleExportClientLedgerPDF = (client: Client) => {
    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const stats = getClientStats(client.id);

      // Top Header Plate
      doc.setFillColor(15, 23, 42); // Slate 900
      doc.rect(0, 0, 210, 45, 'F');

      // Title & Header info
      doc.setTextColor(255, 255, 255);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(16);
      doc.text('LAPORAN MUTASI & PERNYATAAN PIUTANG KLIEN', 14, 18);
      
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(148, 163, 184);
      doc.text('CUSTOMER ACCOUNT STATEMENT & DEBT LEDGER', 14, 23);
      doc.text(`Dicetak pada: ${formatDateIndonesian(new Date().toISOString().split('T')[0])}`, 14, 28);
      doc.text(`Instansi Penerbit: ${user.businessName || user.fullName || 'Usaha Mandiri'}`, 14, 33);
      doc.text(`Alamat Kantor: ${user.address || '-'}`, 14, 38);

      // Client Profile Info Card
      doc.setTextColor(15, 23, 42);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('INFORMASI PROFIL KLIEN:', 14, 55);

      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.rect(14, 58, 182, 34, 'FD');

      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.text(client.name, 20, 65);
      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      doc.text(client.businessName || 'Freelance / Klien Individu', 20, 70);

      doc.setFontSize(8.5);
      doc.text('Email Resmi:', 20, 77);
      doc.setTextColor(15, 23, 42);
      doc.text(client.email, 48, 77);

      doc.setTextColor(100, 116, 139);
      doc.text('Nomor WhatsApp:', 20, 82);
      doc.setTextColor(15, 23, 42);
      doc.text(client.phone || '-', 48, 82);

      doc.setTextColor(100, 116, 139);
      doc.text('Alamat Penagihan:', 20, 87);
      doc.setTextColor(15, 23, 42);
      doc.text(client.address || '-', 48, 87);

      // Financial Summary Block for Client
      doc.setFillColor(stats.unpaidSum > 0 ? 254 : 240, stats.unpaidSum > 0 ? 242 : 253, stats.unpaidSum > 0 ? 242 : 250); // red tint vs green tint
      doc.rect(14, 98, 182, 18, 'F');

      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text('RINGKASAN POSISI KEUANGAN KLIEN:', 18, 103);

      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      doc.text('Total Tagihan:', 18, 111);
      doc.setFont('Helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(`${stats.count} Invoice`, 42, 111);

      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      doc.text('Telah Terbayar:', 82, 111);
      doc.setFont('Helvetica', 'bold');
      doc.setTextColor(22, 163, 74);
      doc.text(formatCurrency(stats.paidSum), 108, 111);

      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      doc.text('Sisa Piutang Terutang:', 142, 111);
      doc.setFont('Helvetica', 'bold');
      doc.setTextColor(stats.unpaidSum > 0 ? 220 : 22, stats.unpaidSum > 0 ? 38 : 163, stats.unpaidSum > 0 ? 38 : 74);
      doc.text(formatCurrency(stats.unpaidSum), 178, 111);

      // Table of Invoices
      const tableHeaders = [
        ['No.', 'No. Invoice', 'Tanggal Buat', 'Jatuh Tempo', 'Status Tagihan', 'Nominal Tagihan']
      ];

      const tableData = stats.clientInvoices.map((inv, index) => {
        return [
          formatSeqNumber(index + 1),
          inv.invoiceNumber,
          formatDateIndonesian(inv.date),
          formatDateIndonesian(inv.dueDate),
          inv.status === 'Lunas' ? 'LUNAS (TERBAYAR)' : 'BELUM LUNAS (PIUTANG)',
          formatCurrency(inv.total, inv.currency)
        ];
      });

      autoTable(doc, {
        startY: 122,
        head: tableHeaders,
        body: tableData,
        theme: 'grid',
        headStyles: {
          fillColor: [30, 41, 59],
          textColor: [255, 255, 255],
          fontSize: 8.5,
          fontStyle: 'bold'
        },
        columnStyles: {
          0: { cellWidth: 12, halign: 'center' },
          1: { fontStyle: 'bold' },
          4: { fontStyle: 'bold' },
          5: { cellWidth: 40, halign: 'right', fontStyle: 'bold' }
        },
        styles: {
          fontSize: 8,
          cellPadding: 3.5
        },
        didParseCell: (data) => {
          if (data.column.index === 0) {
            data.cell.styles.halign = 'center';
          } else if (data.column.index === 5) {
            data.cell.styles.halign = 'right';
          } else {
            data.cell.styles.halign = 'left';
          }
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252]
        },
        margin: { left: 14, right: 14 },
        didDrawPage: (data) => {
          doc.setFontSize(8);
          doc.setTextColor(148, 163, 184);
          doc.text(`Mutasi Piutang Resmi - Halaman ${data.pageNumber} dari ${(doc as any).internal.getNumberOfPages()}`, 14, doc.internal.pageSize.height - 10);
        }
      });

      // Signature area on final page
      const finalY = (doc as any).lastAutoTable.finalY || 120;
      if (finalY < doc.internal.pageSize.height - 50) {
        doc.setFont('Helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(71, 85, 105);
        doc.text('Hormat Kami,', 145, finalY + 15);
        doc.text(user.businessName || user.fullName || 'Pihak Manajemen', 145, finalY + 35);
        doc.setDrawColor(203, 213, 225);
        doc.line(145, finalY + 31, 190, finalY + 31);
      }

      doc.save(`Laporan_Piutang_${client.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error('Error generating ledger PDF:', error);
      showToast('Gagal mengekspor laporan mutasi klien.', 'error');
    }
  };

  // Calculations for Development Feature: top analytical stats
  const totalClients = clients.length;
  let totalPaidAll = 0;
  let totalUnpaidAll = 0;
  let topClient: Client | null = null;
  let topPaidVal = -1;

  clients.forEach(c => {
    const stats = getClientStats(c.id);
    totalPaidAll += stats.paidSum;
    totalUnpaidAll += stats.unpaidSum;
    if (stats.paidSum > topPaidVal) {
      topPaidVal = stats.paidSum;
      topClient = c;
    }
  });

  return (
    <div className="space-y-6 font-sans text-left">
      
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
        <div>
          <h1 className="text-2xl font-display font-extrabold text-brand-dark">Manajemen Klien Bisnis</h1>
          <p className="text-xs text-gray-400 mt-1">Daftar kontak bisnis, analisis omset, dan laporan piutang klien Anda</p>
        </div>
        <div className="flex gap-2">
          {/* REPLACE CSV IMPORT BUTTON WITH PRINT READY PDF EXPORTER */}
          <button 
            onClick={handleExportClientListPDF}
            disabled={isExporting}
            className="px-4 py-2.5 bg-brand-primary-light/35 hover:bg-brand-primary-light/60 text-brand-primary font-bold text-xs rounded-xl border border-brand-primary-light flex items-center gap-1.5 cursor-pointer transition-all disabled:opacity-50"
            title="Simpan data klien ke dokumen PDF siap cetak"
          >
            {isExporting ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                <span>Mengekspor PDF...</span>
              </>
            ) : (
              <>
                <FileDown className="w-4 h-4 text-brand-primary" />
                <span>Simpan PDF Direktori</span>
              </>
            )}
          </button>
          
          <button 
            onClick={handleOpenAddForm}
            className="px-5 py-2.5 bg-brand-primary hover:bg-brand-primary-dark text-white font-bold text-xs rounded-xl flex items-center gap-1.5 shadow-md shadow-brand-primary/10 cursor-pointer transition-all"
          >
            <Plus className="w-4.5 h-4.5" />
            Tambah Klien
          </button>
        </div>
      </div>

      {/* ADDITIONAL DEVELOPED FEATURE: Top Analytical statistics cards for high corporate polish */}
      {!selectedClient && (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          
          <div className="bg-white p-4 sm:p-5 rounded-2xl border border-gray-100 shadow-sm hover:shadow-md hover:border-gray-200 transition-all duration-300 flex flex-col justify-between min-w-0">
            <div className="flex justify-between items-center w-full mb-2">
              <p className="text-[10px] font-black text-gray-400 uppercase tracking-wider">Total Klien Bisnis</p>
              <div className="w-8 h-8 bg-indigo-50 text-indigo-600 rounded-lg flex items-center justify-center shrink-0">
                <Users className="w-4.5 h-4.5" />
              </div>
            </div>
            <div className="min-w-0">
              <p className="text-sm min-[375px]:text-base sm:text-lg lg:text-sm xl:text-base 2xl:text-lg font-display font-extrabold text-brand-dark mt-0.5 truncate">{totalClients} Mitra</p>
              <p className="text-[9px] text-indigo-600 font-bold mt-0.5">🟢 100% Terintegrasi</p>
            </div>
          </div>

          <div className="bg-white p-4 sm:p-5 rounded-2xl border border-gray-100 shadow-sm hover:shadow-md hover:border-gray-200 transition-all duration-300 flex flex-col justify-between min-w-0">
            <div className="flex justify-between items-center w-full mb-2">
              <p className="text-[10px] font-black text-gray-400 uppercase tracking-wider">Pendapatan Lunas</p>
              <div className="w-8 h-8 bg-emerald-50 text-emerald-600 rounded-lg flex items-center justify-center shrink-0">
                <TrendingUp className="w-4.5 h-4.5" />
              </div>
            </div>
            <div className="min-w-0">
              <p className="text-sm min-[375px]:text-base sm:text-lg lg:text-sm xl:text-base 2xl:text-lg font-display font-black text-emerald-600 font-mono mt-0.5 tracking-tight whitespace-nowrap overflow-x-auto scrollbar-none" title={formatCurrency(totalPaidAll)}>
                {formatCurrency(totalPaidAll)}
              </p>
              <p className="text-[9px] text-emerald-600 font-bold mt-0.5">📈 Rasio Lunas: {Math.round((totalPaidAll / (totalPaidAll + totalUnpaidAll || 1)) * 100)}%</p>
            </div>
          </div>

          <div className="bg-white p-4 sm:p-5 rounded-2xl border border-gray-100 shadow-sm hover:shadow-md hover:border-gray-200 transition-all duration-300 flex flex-col justify-between min-w-0">
            <div className="flex justify-between items-center w-full mb-2">
              <p className="text-[10px] font-black text-gray-400 uppercase tracking-wider">Piutang Berjalan</p>
              <div className="w-8 h-8 bg-rose-50 text-rose-600 rounded-lg flex items-center justify-center shrink-0">
                <AlertCircle className="w-4.5 h-4.5" />
              </div>
            </div>
            <div className="min-w-0">
              <p className="text-sm min-[375px]:text-base sm:text-lg lg:text-sm xl:text-base 2xl:text-lg font-display font-black text-rose-600 font-mono mt-0.5 tracking-tight whitespace-nowrap overflow-x-auto scrollbar-none" title={formatCurrency(totalUnpaidAll)}>
                {formatCurrency(totalUnpaidAll)}
              </p>
              <p className="text-[9px] text-rose-500 font-bold mt-0.5">⚠️ Rasio Piutang: {Math.round((totalUnpaidAll / (totalPaidAll + totalUnpaidAll || 1)) * 100)}%</p>
            </div>
          </div>

          <div className="bg-white p-4 sm:p-5 rounded-2xl border border-gray-100 shadow-sm hover:shadow-md hover:border-gray-200 transition-all duration-300 flex flex-col justify-between min-w-0">
            <div className="flex justify-between items-center w-full mb-2">
              <p className="text-[10px] font-black text-gray-400 uppercase tracking-wider">Klien Premium Utama</p>
              <div className="w-8 h-8 bg-amber-50 text-amber-600 rounded-lg flex items-center justify-center shrink-0">
                <Award className="w-4.5 h-4.5" />
              </div>
            </div>
            <div className="min-w-0">
              <p className="text-xs min-[375px]:text-sm sm:text-sm xl:text-base font-display font-extrabold text-brand-dark mt-0.5 truncate max-w-full" title={topClient ? topClient.name : '-'}>
                {topClient ? topClient.name : '-'}
              </p>
              <p className="text-[9px] text-amber-600 font-bold mt-0.5">🏆 {topPaidVal > 0 ? getClientTier(topPaidVal).label : 'Mitra Baru'}</p>
            </div>
          </div>

        </div>
      )}

      {/* Main split dashboard view */}
      {!selectedClient ? (
        <div className="space-y-6">
          {/* Search bar */}
          <div className="bg-white p-4 rounded-2xl border border-gray-100 shadow-sm relative">
            <input 
              type="text" 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Cari klien berdasarkan nama atau nama bisnis..."
              className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-gray-200 text-xs focus:border-brand-primary outline-none transition-all"
            />
            <Search className="absolute left-7 top-6.5 w-4.5 h-4.5 text-gray-400" />
          </div>

          {/* Grid of Client cards */}
          {filteredClients.length === 0 ? (
            <div className="bg-white p-16 rounded-2xl border border-gray-100 shadow-sm text-center text-gray-500">
              <p className="text-sm">Tidak ada klien terdaftar.</p>
              <button onClick={handleOpenAddForm} className="mt-3 px-4 py-2 bg-brand-primary-light text-brand-primary font-bold text-xs rounded-xl cursor-pointer">Buat Klien Pertama Anda</button>
            </div>
          ) : (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredClients.map(c => {
                const stats = getClientStats(c.id);
                return (
                  <div key={c.id} className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-all flex flex-col justify-between text-left relative group">
                    <div className="space-y-4">
                      <div className="flex justify-between items-start">
                        <div className="w-10 h-10 rounded-xl bg-brand-primary-light text-brand-primary flex items-center justify-center font-display font-black text-sm">
                          {c.name.split(' ').map(n=>n[0]).join('').substring(0,2)}
                        </div>
                        <div className="flex flex-col items-end gap-1">
                          <span className={`text-[9px] px-2 py-0.5 rounded-full font-bold border transition-all ${getClientTier(stats.paidSum).classes}`} title={`Level Klien: ${getClientTier(stats.paidSum).label}`}>
                            {getClientTier(stats.paidSum).badge}
                          </span>
                          <div className="flex gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity mt-1">
                            <button onClick={() => handleOpenEditForm(c)} className="p-1 text-gray-400 hover:text-brand-primary cursor-pointer" title="Ubah Profil"><Edit className="w-3.5 h-3.5" /></button>
                            <button onClick={() => triggerDeleteClient(c.id, c.name)} className="p-1 text-gray-400 hover:text-red-500 cursor-pointer" title="Hapus"><Trash2 className="w-3.5 h-3.5" /></button>
                          </div>
                        </div>
                      </div>

                      <div>
                        <h3 className="font-display font-bold text-base text-brand-dark">{c.name}</h3>
                        <p className="text-xs text-gray-400 flex items-center gap-1 mt-0.5">
                          <Briefcase className="w-3.5 h-3.5" />
                          {c.businessName || 'Freelance / Individu'}
                        </p>
                      </div>

                      <div className="space-y-1.5 text-xs text-gray-500">
                        <p className="flex items-center gap-1.5">
                          <Mail className="w-3.5 h-3.5 shrink-0" />
                          <span className="truncate">{c.email}</span>
                        </p>
                        <p className="flex items-center gap-1.5">
                          <Phone className="w-3.5 h-3.5 shrink-0" />
                          <span>{c.phone}</span>
                        </p>
                      </div>
                    </div>

                    <div className="mt-6 pt-4 border-t border-gray-100 grid grid-cols-3 gap-2 text-xs">
                      <div>
                        <p className="text-[9px] text-gray-400 uppercase font-black tracking-wider">Transaksi</p>
                        <p className="font-extrabold text-gray-700 mt-0.5">{stats.count} Inv</p>
                      </div>
                      <div className="min-w-0">
                        <p className="text-[9px] text-gray-400 uppercase font-black tracking-wider">Total Lunas</p>
                        <p className="font-extrabold text-emerald-600 font-mono mt-0.5 text-[11px] tracking-tight whitespace-nowrap overflow-x-auto scrollbar-none" title={formatCurrency(stats.paidSum)}>
                          {formatCurrency(stats.paidSum)}
                        </p>
                      </div>
                      <div className="min-w-0">
                        <p className="text-[9px] text-gray-400 uppercase font-black tracking-wider">Sisa Piutang</p>
                        <p className={`font-extrabold font-mono mt-0.5 text-[11px] tracking-tight whitespace-nowrap overflow-x-auto scrollbar-none ${stats.unpaidSum > 0 ? 'text-rose-600 font-black' : 'text-gray-400 font-medium'}`} title={formatCurrency(stats.unpaidSum)}>
                          {stats.unpaidSum > 0 ? formatCurrency(stats.unpaidSum) : 'Lunas'}
                        </p>
                      </div>
                    </div>

                    <button 
                      onClick={() => setSelectedClient(c)}
                      className="w-full mt-4 py-2 bg-gray-50 hover:bg-brand-primary hover:text-white text-gray-700 text-xs font-bold rounded-xl transition-all flex items-center justify-center gap-1 cursor-pointer"
                    >
                      <span>Lihat Detail & Riwayat</span>
                      <ArrowLeft className="w-3.5 h-3.5 rotate-180" />
                    </button>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      ) : (
        // Client details sheet
        <div className="grid lg:grid-cols-12 gap-8 text-left animate-fade-in">
          
          {/* Back button and profile left */}
          <div className="lg:col-span-4 bg-white p-6 rounded-2xl border border-gray-100 shadow-sm space-y-6">
            <button 
              onClick={() => setSelectedClient(null)}
              className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-brand-primary font-bold cursor-pointer transition-all"
            >
              <ArrowLeft className="w-4 h-4" />
              Kembali ke Daftar Klien
            </button>

            <div className="text-center space-y-3 pb-6 border-b border-gray-50">
              <div className="w-20 h-20 rounded-full bg-brand-primary-light text-brand-primary flex items-center justify-center font-display font-black text-2xl mx-auto shadow-inner relative">
                {selectedClient.name.split(' ').map(n=>n[0]).join('').substring(0,2)}
                <span className="absolute -bottom-1.5 -right-1.5 bg-brand-primary text-white text-[9px] px-1.5 py-0.5 rounded-full font-black border border-white shadow-sm">
                  ID
                </span>
              </div>
              <div className="space-y-1">
                <h2 className="text-lg font-extrabold text-brand-dark leading-tight">{selectedClient.name}</h2>
                <p className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">{selectedClient.businessName || 'Individu / Freelance'}</p>
                
                {/* LOYALTY TIER BADGE IN DETAIL PANEL */}
                <div className="pt-1.5 flex justify-center">
                  <span className={`text-[10px] px-2.5 py-0.5 rounded-full font-bold border flex items-center gap-1 ${getClientTier(getClientStats(selectedClient.id).paidSum).classes}`}>
                    <span>{getClientTier(getClientStats(selectedClient.id).paidSum).badge}</span>
                    <span className="text-[8px] opacity-75">{getClientTier(getClientStats(selectedClient.id).paidSum).score}</span>
                  </span>
                </div>
              </div>
            </div>

            <div className="space-y-4 text-xs">
              <h3 className="font-bold text-gray-400 uppercase tracking-wider text-[10px]">Kontak Resmi</h3>
              
              <div className="space-y-3 text-gray-600">
                <p className="flex items-center gap-2">
                  <Mail className="w-4 h-4 text-brand-primary shrink-0" />
                  <span className="truncate" title={selectedClient.email}>{selectedClient.email}</span>
                </p>
                
                {/* WHATSAPP RICH REMINDER NOTIFICATION FOR FASTER BILLING */}
                <div className="flex items-center justify-between gap-2">
                  <p className="flex items-center gap-2">
                    <Phone className="w-4 h-4 text-brand-primary shrink-0" />
                    <span>{selectedClient.phone || '-'}</span>
                  </p>
                  {selectedClient.phone && getClientStats(selectedClient.id).unpaidSum > 0 && (
                    <a
                      href={`https://api.whatsapp.com/send?phone=${selectedClient.phone.replace(/[^0-9]/g, '').replace(/^0/, '62')}&text=${encodeURIComponent(
                        `Halo *${selectedClient.name}*, kami ingin mengingatkan bahwa terdapat tagihan berjalan Anda di *${user.businessName || user.fullName || 'Usaha Mandiri'}* sebesar *${formatCurrency(getClientStats(selectedClient.id).unpaidSum)}*. Mohon kesediaannya untuk melakukan pembayaran. Terima kasih!`
                      )}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="px-2 py-1 bg-green-50 hover:bg-green-100 text-green-700 font-bold text-[10px] rounded-lg border border-green-200 flex items-center gap-1.5 shrink-0 transition-colors cursor-pointer"
                      title="Kirim pengingat tagihan ramah lewat WhatsApp"
                    >
                      <span className="w-1.5 h-1.5 bg-green-500 rounded-full animate-ping"></span>
                      <span>Tagih via WA</span>
                    </a>
                  )}
                </div>

                <p className="flex items-start gap-2 leading-relaxed">
                  <MapPin className="w-4 h-4 text-brand-primary shrink-0 mt-0.5" />
                  <span>{selectedClient.address || '-'}</span>
                </p>
              </div>

              {/* PAYMENT COLLECTION HEALTH METRICS PROGRESS BAR */}
              <div className="pt-4 border-t border-gray-50 space-y-2">
                <div className="flex justify-between items-center text-[10px]">
                  <span className="text-gray-400 font-bold uppercase tracking-wider">Kolektibilitas / Rasio Pelunasan</span>
                  <span className="font-mono font-black text-brand-primary">
                    {Math.round(
                      (getClientStats(selectedClient.id).paidSum / 
                        (getClientStats(selectedClient.id).paidSum + getClientStats(selectedClient.id).unpaidSum || 1)) * 100
                    )}%
                  </span>
                </div>
                <div className="w-full bg-gray-100 rounded-full h-2 overflow-hidden flex">
                  <div 
                    className="bg-emerald-500 h-full transition-all duration-500" 
                    style={{ 
                      width: `${Math.round(
                        (getClientStats(selectedClient.id).paidSum / 
                          (getClientStats(selectedClient.id).paidSum + getClientStats(selectedClient.id).unpaidSum || 1)) * 100
                      )}%` 
                    }}
                  />
                  <div 
                    className="bg-rose-400 h-full transition-all duration-500" 
                    style={{ 
                      width: `${Math.round(
                        (getClientStats(selectedClient.id).unpaidSum / 
                          (getClientStats(selectedClient.id).paidSum + getClientStats(selectedClient.id).unpaidSum || 1)) * 100
                      )}%` 
                    }}
                  />
                </div>
                <p className="text-[9px] text-gray-400 italic">
                  *Hijau menunjukkan rasio lunas terbayar, merah adalah piutang aktif
                </p>
              </div>

              <div className="pt-4 border-t border-gray-50 flex flex-col gap-2.5">
                <button 
                  onClick={() => handleOpenEditForm(selectedClient)} 
                  className="w-full py-2.5 rounded-xl bg-gray-50 hover:bg-gray-100 text-gray-600 font-bold text-xs border border-gray-200 cursor-pointer transition-colors"
                >
                  Ubah Profil Klien
                </button>

                {/* ADDITIONAL DEVELOPED FEATURE: Statement of Account / Mutasi Piutang PDF Button */}
                <button 
                  onClick={() => handleExportClientLedgerPDF(selectedClient)} 
                  className="w-full py-2.5 rounded-xl bg-slate-800 hover:bg-slate-900 text-white font-bold text-xs flex items-center justify-center gap-1.5 cursor-pointer shadow-md shadow-slate-900/10 transition-colors"
                >
                  <Printer className="w-4 h-4" />
                  Cetak Mutasi Piutang (PDF)
                </button>
              </div>
            </div>
          </div>

          {/* Historical client invoices right */}
          <div className="lg:col-span-8 bg-white p-6 sm:p-8 rounded-2xl border border-gray-100 shadow-sm space-y-6">
            <div>
              <h3 className="font-display font-extrabold text-base text-brand-dark">Riwayat Tagihan Klien</h3>
              <p className="text-xs text-gray-400 mt-1">Daftar invoice dan mutasi piutang yang diterbitkan untuk klien ini</p>
            </div>

            {/* Stats Summary for selected client */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 p-4 rounded-2xl bg-gray-50 border border-gray-100/80 text-xs">
              <div className="min-w-0">
                <p className="text-gray-400 font-bold uppercase text-[9px] tracking-wider">Jumlah Invoice</p>
                <p className="text-base sm:text-lg font-extrabold text-brand-dark mt-1 font-mono truncate">{getClientStats(selectedClient.id).count} Inv</p>
              </div>
              <div className="min-w-0">
                <p className="text-gray-400 font-bold uppercase text-[9px] tracking-wider">Lunas Terbayar</p>
                <p className="text-xs sm:text-sm xl:text-base font-black text-emerald-600 mt-1 font-mono tracking-tight whitespace-nowrap overflow-x-auto scrollbar-none" title={formatCurrency(getClientStats(selectedClient.id).paidSum)}>
                  {formatCurrency(getClientStats(selectedClient.id).paidSum)}
                </p>
              </div>
              <div className="min-w-0">
                <p className="text-gray-400 font-bold uppercase text-[9px] tracking-wider">Sisa Piutang</p>
                <p className={`text-xs sm:text-sm xl:text-base font-black mt-1 font-mono tracking-tight whitespace-nowrap overflow-x-auto scrollbar-none ${getClientStats(selectedClient.id).unpaidSum > 0 ? 'text-rose-600 font-black' : 'text-gray-500'}`} title={formatCurrency(getClientStats(selectedClient.id).unpaidSum)}>
                  {formatCurrency(getClientStats(selectedClient.id).unpaidSum)}
                </p>
              </div>
            </div>

            {/* List invoices with interactive filter options */}
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-gray-100 pb-2">
                <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">Daftar Invoice Terbit</span>
                <div className="flex gap-1.5 bg-gray-100 p-0.5 rounded-lg">
                  {(['Semua', 'Lunas', 'Pending'] as const).map((f) => (
                    <button
                      key={f}
                      type="button"
                      onClick={() => setInvoiceFilter(f)}
                      className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all cursor-pointer ${
                        invoiceFilter === f
                          ? 'bg-white text-brand-dark shadow-xs'
                          : 'text-gray-400 hover:text-gray-600'
                      }`}
                    >
                      {f}
                    </button>
                  ))}
                </div>
              </div>

              {getClientStats(selectedClient.id).clientInvoices.length === 0 ? (
                <p className="text-xs text-gray-400 italic py-6 text-center bg-gray-50/50 rounded-2xl border border-dashed border-gray-200">Belum ada invoice yang diterbitkan untuk klien ini.</p>
              ) : (
                <div className="divide-y divide-gray-100 border border-gray-100 rounded-2xl overflow-hidden bg-white">
                  {getClientStats(selectedClient.id)
                    .clientInvoices.filter((inv) => {
                      if (invoiceFilter === 'Lunas') return inv.status === 'Lunas';
                      if (invoiceFilter === 'Pending') return inv.status !== 'Lunas';
                      return true;
                    })
                    .map((inv) => (
                      <div key={inv.id} className="p-4 flex justify-between items-center text-xs hover:bg-gray-50/50 transition-colors">
                        <div>
                          <p className="font-mono font-bold text-brand-dark text-sm">{inv.invoiceNumber}</p>
                          <p className="text-gray-400 text-[10px] mt-1 flex items-center gap-1">
                            <span className="font-bold">Tanggal:</span> {formatDateIndonesian(inv.date)} | <span className="font-bold">Jatuh Tempo:</span> {formatDateIndonesian(inv.dueDate)}
                          </p>
                        </div>
                        <div className="text-right">
                          <p className="font-mono font-black text-brand-dark text-sm">{formatCurrency(inv.total, inv.currency)}</p>
                          <span className={`inline-block text-[10px] px-2 py-0.5 rounded-full font-bold mt-1.5 ${
                            inv.status === 'Lunas' 
                              ? 'bg-emerald-50 text-emerald-700 border border-emerald-100' 
                              : 'bg-rose-50 text-rose-700 border border-rose-100'
                          }`}>
                            {inv.status === 'Lunas' ? 'Lunas ✔' : 'Pending ⏳'}
                          </span>
                        </div>
                      </div>
                    ))}
                  {getClientStats(selectedClient.id).clientInvoices.filter((inv) => {
                    if (invoiceFilter === 'Lunas') return inv.status === 'Lunas';
                    if (invoiceFilter === 'Pending') return inv.status !== 'Lunas';
                    return true;
                  }).length === 0 && (
                    <div className="p-8 text-center text-xs text-gray-400 italic">
                      Tidak ada invoice dengan status "{invoiceFilter}".
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* MODAL: ADD / EDIT CLIENT FORM */}
      {formOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="bg-white rounded-2xl border border-gray-100 shadow-xl max-w-lg w-full p-6 text-left space-y-4 animate-scale-up">
            <div className="flex justify-between items-center border-b border-gray-100 pb-3">
              <h3 className="font-display font-extrabold text-sm text-brand-dark uppercase tracking-wider">{editingClient ? 'Ubah Profil Klien' : 'Tambah Klien Baru'}</h3>
              <button onClick={() => setFormOpen(false)} className="text-gray-400 hover:text-gray-600 text-xl font-bold cursor-pointer">×</button>
            </div>
            
            <form onSubmit={handleSubmit} className="space-y-3">
              <div>
                <label className="block text-[10px] font-bold text-gray-500 uppercase mb-1">Nama Lengkap (Wajib)</label>
                <input required type="text" value={name} onChange={(e) => setName(e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs outline-none focus:border-brand-primary" placeholder="e.g. Budi Santoso" />
              </div>
              
              <div>
                <label className="block text-[10px] font-bold text-gray-500 uppercase mb-1">Nama Perusahaan/Bisnis (Opsional)</label>
                <input type="text" value={businessName} onChange={(e) => setBusinessName(e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs outline-none focus:border-brand-primary" placeholder="e.g. PT Berkah Sukses Abadi" />
              </div>
              
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-[10px] font-bold text-gray-500 uppercase mb-1">Email Klien (Wajib)</label>
                  <input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs outline-none focus:border-brand-primary" placeholder="budi@tokoberkah.com" />
                </div>
                <div>
                  <label className="block text-[10px] font-bold text-gray-500 uppercase mb-1">No. Telepon / WhatsApp</label>
                  <input type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs outline-none focus:border-brand-primary" placeholder="e.g. 08129876543" />
                </div>
              </div>

              <div>
                <label className="block text-[10px] font-bold text-gray-500 uppercase mb-1">Alamat Lengkap Penerima Invoice</label>
                <textarea rows={3} value={address} onChange={(e) => setAddress(e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded-xl text-xs outline-none focus:border-brand-primary resize-none" placeholder="Alamat penagihan lengkap..." />
              </div>

              <div className="pt-4 flex gap-3">
                <button type="button" onClick={() => setFormOpen(false)} className="flex-1 py-2.5 bg-gray-50 text-gray-600 text-xs font-bold rounded-xl border border-gray-200 cursor-pointer">Batal</button>
                <button type="submit" className="flex-1 py-2.5 bg-brand-primary hover:bg-brand-primary-dark text-white font-bold text-xs rounded-xl shadow-md cursor-pointer transition-colors">Simpan Klien</button>
              </div>
            </form>
          </div>
        </div>
      )}

      <ConfirmModal
        isOpen={confirmDeleteState.isOpen}
        onClose={() => setConfirmDeleteState(prev => ({ ...prev, isOpen: false }))}
        onConfirm={executeDeleteClient}
        title="Hapus Klien"
        message={`Apakah Anda yakin ingin menghapus klien ${confirmDeleteState.clientName} secara permanen? Seluruh riwayat transaksi yang terkait dengan klien ini mungkin terpengaruh.`}
        confirmText="Ya, Hapus"
        cancelText="Batal"
        type="danger"
      />

    </div>
  );
}
